# Generated by Django 6.0.6 on 2026-06-29 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_student_address_student_enrolled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
