# Generated by Django 4.2.21 on 2025-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default='DEFAULT001', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.CharField(default='Default Course Title', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_photos/'),
        ),
    ]
